FrontEnd/Controllers/CarritoController.cs
using BackEnd.BLL.Productos;
using BackEnd.Model;
using FrontEnd.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    public class CarritoController : Controller
    {

        private Mapeos mapeo = new Mapeos();
        IProductoBLL productoBLL;


        public CarritoController()
        {

            productoBLL = new ProductoBLLImpl();
        }

        public ActionResult Index()
        {
            return View((List<ProductoViewModel>)Session["cart"]);
        }

        public ActionResult Eliminar(int id)
        {
            List<ProductoViewModel> li = (List<ProductoViewModel>)Session["cart"];
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;

            T_productos producto = new T_productos();
            producto = productoBLL.Get(id);

            var itemToRemove = li.FirstOrDefault(r => r.codigo == id);
            li.Remove(itemToRemove);

            Session["cart"] = li;

            return RedirectToAction("Index");
        }
    }
}

FrontEnd/Controllers/LoginController.cs
using BackEnd.BLL;
using FrontEnd.Models;
using System;
using System.Collections.Generic;
using System.Linq;

using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace FrontEnd.Controllers
{
    public class LoginController : Controller
    {



        private IUserBLL userBLL;

        //
        // GET: /Login/
        public ActionResult Index()
        {
            return View();
        }



        [HttpPost]
        public ActionResult Autherize(UserViewModel userModel)
        {

            userBLL = new UserBLLImpl();
            var userDetails = userBLL.getUser(userModel.UserName, userModel.Password);


            Session.Abandon();
            FormsAuthentication.SignOut();


            if (userDetails == null)
            {
                userModel.LoginErrorMessage = "Nombre de Usuario o Password Incorrectos";
                return View("Index", userModel);
            }
            else
            {

                Session["userID"] = userDetails.UserId;
                Session["userName"] = userDetails.UserName;
                var authTicket = new FormsAuthenticationTicket(userDetails.UserName, true, 100000);
                var cookie = new HttpCookie(FormsAuthentication.FormsCookieName,
                                            FormsAuthentication.Encrypt(authTicket));
                Response.Cookies.Add(cookie);
                var name = User.Identity.Name; // line 4
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult LogOut()
        {
            //int userId = (int)Session["userID"];
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }


    }
}

FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Le Negre", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Catalogo", "Index", "Catalogo")</li>


                    @if (ViewContext.HttpContext.User.IsInRole("Administrador"))
                    {
                        <li>@Html.ActionLink("Usuarios", "Index", "Persona")</li>
                        <li>@Html.ActionLink("Productos", "Index", "Producto")</li>
                        <li>@Html.ActionLink("Proveedores", "Index", "Proveedor")</li>
                    }



                   
                </ul>
                <ul class="nav navbar-nav navbar-right">


                    <li>@Html.ActionLink("Contactenos", "Contacto", "Home")</li>

                    <li>@Html.ActionLink("Carrito " + @Session["count"], "Index", "Carrito")</li>
                    @{
                        if (String.IsNullOrEmpty(User.Identity.Name))
                        {
                            <li>@Html.ActionLink("Iniciar Sesión", "Index", "Login")</li>
                        }
                        else
                        {
                            <li class="navbar-text">¡Hola, @User.Identity.Name!</li>

                            <li>@Html.ActionLink("Cerrar Sesión", "Logout", "Login")</li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>